data/urls.py
# data/urls.py
from django.urls import path
from . import views
# from .views import ActivityListView

app_name = 'data'

urlpatterns = [

    # path('activities/', ActivityListView.as_view(), name='list_activities'),
    path('activity/new/', views.activity_create, name = 'create_activity'),
    path('acitivity/edit/<int:pk>/', views.activity_edit, name='update_activity'),

    # dynamic views
    path('activities/<int:pk>', views.activity_view ,name='view_activities'),
    path('activities/<int:pk>/new/', views.activity_new, name='new_activity'),

]

npt_data/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('datasets.urls')),
    path('data/', include('data.urls')),
    path('locs/', include('locations.urls')),
]

data/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datasets.models import AuditParent, AuditChild

# Create your models here.

class Parent(AuditParent):
    survey_date = models.DateField()
    species = models.CharField(max_length = 20, choices=(("Sp/sm Chinook", "Sp/sm Chinook"), ("Fall Chinook", "Fall Chinook"), ("Coho", "Coho"), ("Sockeye", "Sockeye"), ("Steelhead", "Steelhead")), default= "Sp/sm Chinook")
    surveyors = models.CharField(max_length = 50)
    survey_type = models.CharField(max_length=25, choices=(("Redd and Carcass", "Redd and Carcass"), ("Redd", "Redd"), ("Carcass", "Carcass")), default="Redd and Carcass")
    survey_method = models.CharField(max_length = 25, choices=(("Ground", "Ground"), ("Helicopter","Helicopter"), ("UAV", "UAV")), default="Ground")

    # def save(self, *args, **kwargs):
    #     user = kwargs.pop('user', None)
    #     if user:
    #         if not self.pk: # if self.pk is blank...set created by to user
    #             self.updated_by = user
    #     super(Parent, self).save(*args, **kwargs)
    
    # def get_fields(self):
    #         return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields]
        
    def __str__(self):
        return str(self.id)

class Child1(AuditChild):
    feature_type = models.CharField(max_length=25, choices=(("Redd","Redd"), ("Live Fish", "Live Fish")), default="Redd")
    count = models.IntegerField()
    wpt_name = models.CharField(max_length = 10)
    lat = models.CharField(max_length=20, blank = True, null=True)
    long = models.CharField(max_length=20, blank = True, null=True)

class Child2(AuditChild):
    sample_id = models.CharField(max_length=30, blank=True, null=True)
    sex = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')), default = 'M')
    fork_length = models.IntegerField()
    lat = models.CharField(max_length=20, blank = True, null=True)
    long = models.CharField(max_length=20, blank = True, null=True)


class TrapHeader(AuditParent):
    trap_date = models.DateField()

    def __str__(self):
        return str(self.id)
    
class TrapDetail(AuditChild):
    species = models.CharField(max_length=30)

    def __str__(self):
        return str(self.id)

data/forms.py
from django import forms
from django.forms import ModelForm
from .models import Parent, Child1, Child2

class ParentForm(ModelForm):
    class Meta:
        model = Parent
        fields = ['protocol', 'task', 'location', 'publish_status', 'survey_date', 'species', 'surveyors', 'survey_type', 'survey_method']

class Child1Form(ModelForm):
    class Meta:
        model = Child1
        fields = ['feature_type', 'count', 'wpt_name', 'lat', 'long']

class Child2Form(ModelForm):
    class Meta:
        model = Child2
        fields = ['sample_id', 'sex', 'fork_length', 'lat', 'long']

data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.apps import apps
import requests
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView

from data.models import Parent
from datasets.models import Activity, DatasetModel, DatasetField
from datasets.forms import ActivityForm
from .forms import  ParentForm, Child1Form, Child2Form


# Activities

# class ActivityListView(ListView):
#     model = Activity
#     template_name = 'data/activity_list.html'

def activity_view(request, pk):
    dataset = DatasetModel.objects.get(dataset = pk, parent_model=True)
    model= apps.get_model(app_label='data', model_name = dataset.model_name)
    fields = model._meta.get_fields()
    # activities = model.objects.all()
    activities = model.objects.values()
    context = {'dataset':dataset,'fields':fields, 'activities':activities}
    return render(request, "data/dataset_activities.html", context)

def activity_new(request, pk):
    models = DatasetModel.objects.filter(dataset = pk)

    if request.method == 'POST':
        activity_form = ActivityForm(request.POST)
        if activity_form.is_valid():
            activity=activity_form.save(commit=False)
            activity.created_by = request.user
            activity.dataset = pk
            activity.save()

            return redirect('data:view_activities')
        
    activity_form = ActivityForm(request.POST)
            
    context = {'models':models, 'activity_form':activity_form}
    return render(request, "data/activity_create_or_update.html",context)


def activity_create(request):
    if request.method == 'POST':
        activity_form = ActivityForm(request.POST)
        parent_form = ParentForm(request.POST)
        child1_form = Child1Form(request.POST)
        child2_form = Child2Form(request.POST)
        if activity_form.is_valid() and parent_form.is_valid() and child1_form.is_valid() and child2_form.is_valid():
            activity=activity_form.save(commit=False)
            activity.created_by = request.user
            activity.save()
       
            parent=parent_form.save(commit=False)
            parent.activity = activity
            parent.updated_by = request.user
            parent.save()

            child1=child1_form.save(commit=False)
            child1.activity = activity
            child1.updated_by = request.user
            child1.row_id = 1
            child1.save()

            child2=child2_form.save(commit=False)
            child2.activity = activity
            child2.updated_by = request.user
            child2.row_id = 1
            child2.save()

            return redirect('data:view_activities')

    activity_form = ActivityForm(request.POST)
    parent_form = ParentForm(request.POST)
    child1_form = Child1Form(request.POST)
    child2_form = Child2Form(request.POST)
    context = {'activity_form':activity_form, 'parent_form':parent_form, 'child1_form':child1_form, 'child2_form':child2_form}
    return render(request, "data/activity_new.html", context)

def activity_edit(request, pk):
    parent = get_object_or_404(Parent, pk=pk)
    if request.method == 'POST':
        #activity_form = ActivityForm(request.POST)
        parent_form = ParentForm(request.POST, instance=parent)
        child1_form = Child1Form(request.POST)
        child2_form = Child2Form(request.POST)
        if parent_form.is_valid() and child1_form.is_valid() and child2_form.is_valid():
           
            parent=parent_form.save(commit=False)
            parent.updated_by = request.user
            parent.pk = None
            parent.save()

            child1=child1_form.save(commit=False)
            child1.updated_by = request.user
            child1.pk = None
            child1.save()

            child2=child2_form.save(commit=False)
            child2.updated_by = request.user
            child2.pk = None
            child2.save()
            
            return redirect('data:activity_list')

    parent_form = ParentForm(instance=parent)
    child1_form = Child1Form(instance=child1)
    child2_form = Child2Form(instance=child2)
    context = {'parent_form':parent_form, 'child1_form':child1_form, 'child2_form':child2_form}
    return render(request, "data/activity_new.html", context)

templates/data/activity_create_or_update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1>New/Edit Acitivity</h1>

{% for model in models %}
    {% if forloop.first %}
        <h1>{{ model.dataset }}</h1>
    {% endif %}
    <p>{{ model.model_name }}</p>
{% endfor %}

<form enctype="multipart/form-data" class="container" method="post" id="activity_form">
    {% csrf_token %}
    {{ activity_form.as_p }}
</form>


</div>
{% endblock %}

templates/data/activity_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <h1>Activities</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="{% url 'data:create_activity' %}" class='btn btn-primary'>Add New Item</a>
    </div>
  </div>
</div>

<div class="container">
{% if object_list %}
<table class="table table-striped">
  <thead>
    <tr>
        <th>pk</th>   
        <th>Activity</th> 
        <th>Dataset</th> 
        <th>Created By</th>
        <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    {% for i in object_list %}
    <tr>
        <td>{{ i.pk }}</td>
        <td>{{ i.activity.id }}</td>
        <td>{{ i.activity.dataset.name }}</td>
        <td>{{ i.activity.created_by }}</td>
        <td>{{ i.activity.created_at }}</td>
    </tr>
  </tbody>
    {% endfor %}
</table>
{% else %}
<p>There are no data entries. Please return to the dataset page and create a new activity.</p>
{% endif %}

</div>
{% endblock %}

templates/data/activity_new.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
	<h1>New Model Form</h1>
	<ul class="nav nav-tabs">
		<li class="nav-item">
		  <a class="nav-link active" aria-current="page" href="#">Active</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="#">Link</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="#">Link</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
		</li>
	  </ul>
	<form method="POST">
		{% csrf_token %}
		<div class="container">
        {% if activity_form %}
		    {{ activity_form.as_p }}
        {% endif %}
		</div>
		<div class="container">
        	{{ parent_form.as_p }}
		</div>
		<div class="container">
			{{ child1_form.as_p }}
			{{ child2_form.as_p }}
		<div class="container">
		<button class="btn btn-primary">Post</button>
	</form>
</div>
{% endblock %}

templates/data/dataset_activities.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <h1>{{ dataset.dataset.name }}: {{ dataset.dataset.id }}</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="{% url 'data:new_activity' dataset.dataset.id %}" class='btn btn-success'>Add Dynamic New Activity</a>
    </div>
  </div>
</div>

</br>

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="{% url 'data:create_activity' %}" class='btn btn-primary'>Add New Activity</a>
    </div>
  </div>
</div>

{% if activities %}
<div class="container">
  <table class="table table-striped">
    {% for instance in activities %}
      {% if forloop.first %}
      <thead>
        <tr>
          {% for key, value in instance.items%}
            <th>{{ key }}</th>
          {% endfor %}
            <th>Edit</th>
            <th>Delete</th>
          </th>
        </tr>
      </thead>
      {% endif %}
      <tbody>
        <tr>
          {% for key, value in instance.items %}
            <td>{{ value }}</td>
          {% endfor %}
          <td><a href="{% url 'data:update_activity' pk=instance.id %}">Edit</a></td>
          <td><a href="{% url 'data:update_activity' pk=instance.id %}">Delete</a></td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no data entries, please create a new activity.</p>
  {% endif %}
</div>

{% endblock %}