data/urls.py
# data/urls.py
from django.urls import path
from . import views
# from .views import ActivityListView

app_name = 'data'

urlpatterns = [

    # path('activities/', ActivityListView.as_view(), name='list_activities'),
    path('activity/new/', views.activity_create, name = 'create_activity'),
    path('acitivity/edit/<int:pk>/', views.activity_edit, name='update_activity'),

    # dynamic views
    path('activities/<int:pk>', views.activity_view ,name='view_activities'),
    path('activities/<int:pk>/new/', views.activity_new, name='new_activity'),

]

datasets/urls.py
# datasets.urls

# data/urls.py
from django.urls import path
from . import views

from .views import home, DatasetList, DatasetCreate, DatasetUpdate, delete_model, update_fields, ProtocolList, ProtocolCreate, ProtocolUpdate, TaskList, TaskCreate, TaskUpdate

app_name = 'datasets'

urlpatterns = [
    path('',home,name='home'),
    path('datasets/', DatasetList.as_view(), name='list_datasets'),
    path('datasets/create/', DatasetCreate.as_view(), name='create_dataset'),
    path('datasets/update/<int:pk>/', DatasetUpdate.as_view(), name='update_dataset'),
    path('datasets/delete-model/<int:pk>/', delete_model, name='delete_model'),
    path('datasets/model/<int:pk>/', update_fields, name='update_fields'),

    path('protocols/', ProtocolList.as_view(), name='list_protocols'),
    path('protocols/create/', ProtocolCreate.as_view(), name='create_protocol'),
    path('protocols/update/<int:pk>/', ProtocolUpdate.as_view(), name='update_protocol'),

    path('tasks/', TaskList.as_view(), name='list_tasks'),
    path('tasks/create/', TaskCreate.as_view(), name='create_task'),
    path('tasks/update/<int:pk>/', TaskUpdate.as_view(), name='update_task'),
]

npt_data/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('datasets.urls')),
    path('data/', include('data.urls')),
    path('locs/', include('locations.urls')),
]

datasets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from locations.models import Location

# Create your models here.
    
# Task should be imported from other app
class Task(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('datasets:list_tasks')

# Dataset Metadata

class Dataset(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.name

      
class DatasetModel(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, null=True)
    model_name = models.CharField(max_length=100)
    parent_model = models.BooleanField(default=False)
    def __str__(self):
        return self.model_name #dataset.name
    
class DatasetField(models.Model):
    dataset_model = models.ForeignKey(DatasetModel, on_delete=models.CASCADE, null=True)
    field_name = models.CharField(max_length=100)
    description = models.CharField(max_length = 255, blank=True, null=True)
    units = models.CharField(max_length=2)
    data_type = models.CharField(max_length=20)
    form_type = models.CharField(max_length=20)
    validation = models.CharField(max_length=100)
    possible_values = models.CharField(max_length=100)
    order = models.IntegerField()

    def __str__(self):
        return self.field_name

class Protocol(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    date_started = models.DateField()
    date_ended = models.DateField(blank=True, null=True)
    url = models.URLField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('datasets:list_protocols')


# Dataset Auditting

class Activity(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) # adds date at the creation of the record was: auto_now_add=True
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        if user:
            if not self.pk: # if self.pk is blank...set created by to user
                self.created_by = user
        super(Activity, self).save(*args, **kwargs)
        
    def __str__(self):
        return str(self.id)  

class AuditParent(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    protocol = models.ForeignKey(Protocol, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, default=1, null= True, blank=True, on_delete=models.CASCADE, verbose_name = "Location")
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    effective_date = models.DateTimeField(auto_now=True)# updates the value when ever the record is saved/updated
    active_status = models.CharField(max_length=10, choices=(("active", "Active"), ("inactive", "Inactive")), default="active")
    publish_status = models.CharField(max_length=10, choices=(("publish", "Publish"), ("draft", "Draft")), default="draft")

    class Meta:
        abstract = True
        ordering = ('-activity', "-effective_date", "active_status")

    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        if user:
            self.updated_by = user
        if not self.pk: # if pk is blank set status to active
            self.active_status = "active"
        super().save(*args, **kwargs)
        self.__class__.objects.filter(activity_id=self.activity_id, active_status="active").exclude(effective_date=self.effective_date).update(active_status="inactive")


class AuditChild(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    effective_date = models.DateTimeField(auto_now=True)# updates the value when ever the record is saved/updated
    active_status = models.CharField(max_length=10, choices=(("active", "Active"), ("inactive", "Inactive")), default="active")
    row_id = models.IntegerField()

    class Meta:
        abstract = True
        ordering = ('-activity', "-effective_date", "active_status")

    def save(self, *args, **kwargs):
        if not self.pk: # if pk is blank set status to active
            self.active_status = "active"
        super().save(*args, **kwargs)
        self.__class__.objects.filter(activity_id=self.activity_id, active_status="active", row_id=self.row_id).exclude(effective_date=self.effective_date).update(active_status="inactive")

datasets/forms.py
# datasets/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory
from .models import Dataset, DatasetModel, DatasetField, Protocol, Task, Activity

# Dataset Forms
class DatasetForm(forms.ModelForm):

    class Meta:
        model = Dataset
        fields = '__all__'
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            }

class DatasetModelForm(forms.ModelForm):

    class Meta:
        model = DatasetModel
        fields = ('model_name', 'parent_model')

DatasetModelFormSet = inlineformset_factory(
    Dataset, DatasetModel, form=DatasetModelForm,
    extra=1, can_delete=False, can_delete_extra=True
)


class DatasetFieldForm(ModelForm):
    class Meta:
        model = DatasetField
        fields = ('field_name', 'description', 'units', 'data_type', 'form_type', 'validation', 'possible_values', 'order')
        exclude = ('id', 'dataset_model',)

DatasetFieldFormSet = inlineformset_factory(
    DatasetModel,
    DatasetField,
    form=DatasetFieldForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True)


class ProtocolForm(ModelForm):
    class Meta:
        model = Protocol
        fields = '__all__'#('name', 'description', 'date_started', 'date_ended', 'url')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'date_started': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control', 'placeholder': 'Select a date', 'type': 'date'}),
            'date_ended': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control', 'placeholder': 'Select a date', 'type': 'date'}),
            'url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://someplace.com'}),
            }

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            }        

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['dataset']

datasets/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from .forms import DatasetForm, DatasetModelFormSet, DatasetFieldFormSet, ProtocolForm, TaskForm

from .models import Dataset, DatasetModel, Protocol, Task
 
def home(request):
    return render(request, 'home.html', {})

# Dataset Views

class DatasetInline():
    form_class = DatasetForm
    model = Dataset
    template_name = "datasets/dataset_create_or_update.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('datasets:list_datasets')

    def formset_models_valid(self, formset):
        """
        Hook for custom formset saving.Useful if you have multiple formsets
        """
        models = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this 2 lines, if you have can_delete=True parameter 
        # set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for model in models:
            model.dataset = self.object
            model.save()

class DatasetCreate(DatasetInline, CreateView):

    def get_context_data(self, **kwargs):
        ctx = super(DatasetCreate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'models': DatasetModelFormSet(prefix='models'),
            }
        else:
            return {
                'models': DatasetModelFormSet(self.request.POST or None, self.request.FILES or None, prefix='models'),
            }


class DatasetUpdate(DatasetInline, UpdateView):

    def get_context_data(self, **kwargs):
        ctx = super(DatasetUpdate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        return {
            'models': DatasetModelFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='models'),
        }
    
class DatasetList(ListView):
    model = Dataset
    template_name = "datasets/dataset_list.html"
    context_object_name = "datasets"

def delete_model(request, pk):
    try:
        model = DatasetModel.objects.get(id=pk)
    except DatasetModel.DoesNotExist:
        messages.success(
            request, 'Object Does not exit'
            )
        return redirect('datasets:update_dataset', pk=model.dataset.id)

    model.delete()
    messages.success(
            request, 'Image deleted successfully'
            )
    return redirect('datasets:update_dataset', pk=model.dataset.id)

def update_fields(request, pk):
    model = get_object_or_404(DatasetModel, pk=pk)
    # model = DatasetModel.objects.get(pk=pk)
    if request.method == 'POST':
        formset = DatasetFieldFormSet(request.POST, instance=model, prefix='fields')
        
        if formset.is_valid():
            formset.save(commit=True)
            return redirect('datasets:update_dataset', pk=model.dataset.id)
        
    formset = DatasetFieldFormSet(instance=model, prefix='fields')

    context = {'model':model, 'formset':formset}
    return render(request, "datasets/model_detail.html", context)

class ProtocolList(ListView):
    model = Protocol
    template_name = 'datasets/protocol_list.html'
    context_object_name = 'list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

class ProtocolCreate(CreateView):
    model = Protocol
    form_class = ProtocolForm
    template_name = 'datasets/protocol_create_or_update.html'
    context_object_name = 'form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

class ProtocolUpdate(UpdateView):
    model = Protocol
    form_class = ProtocolForm
    template_name = 'datasets/protocol_create_or_update.html'
    context_object_name = 'form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

class TaskList(ListView):
    model = Task
    template_name = 'datasets/task_list.html'
    context_object_name = 'list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

class TaskCreate(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'datasets/protocol_create_or_update.html'
    context_object_name = 'form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

class TaskUpdate(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'datasets/protocol_create_or_update.html'
    context_object_name = 'form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_name'] = self.model.__name__
        return context

templates/datasets/dataset_create_or_update.html
{% extends "base.html" %}

{% block content %}

<form enctype="multipart/form-data" class="container" method="post" id="product_form">
    {% csrf_token %}
    <!-- main form start --- in our case product form -->
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Dataset</h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{field.label}}</label>
                {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                {% endif %}
            
                {{field}}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <!-- Dataset form ends -->

    <!-- DatasetModel inline form start -->

    <!-- EXPLAINING with named_formsets.variants as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here variants is our VariantFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.models as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="models-template">  // id="inlineformsetname-template"
            // id='inlineformsetname-__prefix__' 
            <tr id="models-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Dataset Tables</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>Table Name <span style="color: red;" class="required">*</span></th>
                    <th>Parent/Header Table <span style="color: red;" class="required">*</span></th>
                    {% comment %} <th>Delete?</th> {% endcomment %}
                    <th>Actions</th>
                </thead>
                <tbody id="item-models">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="models-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                    
                                    {% comment %} {{ field.DELETE }} {% endcomment %}
                                </td>
                            {% endfor %}
                            {% comment %} for delete {% endcomment %}
                            {% if formss.instance.pk %}
                                <td>
                                    <a class="btn btn-primary" href="{% url 'datasets:update_fields' formss.instance.pk %}">
                                        Add/Edit Fields
                                    </a>

                                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{formss.instance.pk}}">
                                        Delete Table
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This Model?</h5>
                                            {% comment %} <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span> {% endcomment %}
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'datasets:delete_model' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>            
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="card-footer d-grid gap-2">
            <a href="#" id="add-models-button" class="btn btn-primary add-models">Add Tables</a> <!-- id="add-inlineformsetname-button" -->
            </div>
        </div>
        
        {% endwith %}
        <!-- inline form for Images end -->

        <div class="form-group d-grid gap-2 pt-5">
            <button type="submit" class="btn btn-success btn-block">Save Dataset and Tables</button>
        </div>
</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
  $(document).ready(function() {
    // when user clicks add more btn of variants
      $('.add-models').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-models').children().length;
          var tmplMarkup = $('#models-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-models').append(compiledTmpl);
  
          // update form count
          $('#id_models-TOTAL_FORMS').attr('value', count+1);
      });
  });
</script>
        
{% endblock content %}

templates/datasets/dataset_list.html
<!-- datasets/dataset_list.html -->
{% extends "base.html" %}


{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <div class="container text-center">
            <h4>Hello {{user.username }}!</h4>
            <p><a href="{% url 'logout' %}">Log Out</a></p>
        </div>
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Datasets</h4>
        </div>
        {% if datasets %}
        <table class="table card-body">
            <thead>
                <tr>
                    {% comment %} <th>Dataset Id</th> {% endcomment %}
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead >
            <tbody>
                {% for dataset in datasets %}
                <tr>
                    {% comment %} <td>{{ dataset.id }}</td> {% endcomment %}
                    <td>{{ dataset.name }}</td>
                    <td>{{ dataset.description }}</td>
                    <td><a class="btn btn-success" href="{% url 'data:view_activities' dataset.id %}">View Data</a></td>    
                    <td><a class="btn btn-primary" href="{% url 'datasets:update_dataset' dataset.id %}">Edit Dataset</a></td>    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>There are no data entries, please create a new item.</p>
        {% endif %}
        <div class="card-footer d-grid gap-2">
            <a class="btn btn-primary " href="{% url 'datasets:create_dataset' %}">Add Datasets</a>
        </div>
    </div>

    {% else %}
        <div class="container text-center">
            <p>Please login to view data.</p>
            <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        </div>
{% endif %}   
</div>
{% endblock content %}

templates/datasets/model_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>{{ model.dataset.name }}</h2>
</div>

    <form class="container" enctype="multipart/form-data" method="post" id="field_form">
        {% csrf_token %}
        <div class="table-responsive card mt-4">
                <div class="card-header card-header-secondary">
                    <h4 class="card-title">{{model.model_name}}</h4>
                </div>
            
            {{ formset.management_form }}

            <script type="text/html" id="fields-template">  // id="inlineformsetname-template"
                // id='inlineformsetname-__prefix__' 
                <tr id="fields-__prefix__" class= hide_all>
                    {% for fields in formset.empty_form.hidden_fields %}
                        {{ fields }}
                    {% endfor %}
                
                    {% for fields in formset.empty_form.visible_fields %}
                        <td>{{fields}}</td>
                    {% endfor %}
                </tr>
            </script>


            {% for hidden in formset.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <table class="table card-body">
                <thead class="text-secondary">
                    {% for form in formset.forms %}
                        {% if forloop.first %}
                            {% for field in form.visible_fields %}
                                <th>
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span style="color: red;" class="required">*</span>
                                    {% endif %}
                                </th>
                            {% endfor %}
                        {% endif %}
                </thead>
                <tbody id="item-fields">
                    <tr>
                        {% for field in form %}
                            <td>{{ field }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="card-footer d-grid gap-2">
                <a href="#" id="add-fields-button" class="btn btn-primary add-fields">Add Fields</a> <!-- id="add-inlineformsetname-button" -->
            </div>
        </div>
        
        <div class="form-group d-grid gap-2 pt-5">
            <button type="submit" class="btn btn-success btn-block">Save Fields</button>
        </div>

    </form>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
          // when user clicks add more btn of variants
            $('.add-fields').click(function(ev) {
                ev.preventDefault();
                var count = $('#item-fields').children().length;
                var tmplMarkup = $('#fields-template').html();
                var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                $('#item-fields').append(compiledTmpl);
        
                // update form count
                $('#id_fields-TOTAL_FORMS').attr('value', count+1);
            });
        });
      </script>

    {% comment %} <script>
        let birdForm = document.querySelectorAll(".item-fields")
        let container = document.querySelector("#field_form")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

        let formNum = birdForm.length-1
        addButton.addEventListener('click', addForm)

        function addForm(e){
            e.preventDefault()

            let newForm = birdForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')

            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)
            
            totalForms.setAttribute('value', `${formNum+1}`)
        }
    </script> {% endcomment %}

{% endblock %}

templates/datasets/protocol_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <div class="container text-center">
            <h4>Hello {{user.username }}!</h4>
            <p><a href="{% url 'logout' %}">Log Out</a></p>
        </div>
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">{{ model_name }}</h4>
        </div>

        <table class="table card-body">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead >
            <tbody>
                {% if list %}
                {% for i in list %}
                <tr>
                    <td>{{ i.name }}</td>
                    <td><a class="btn btn-primary" href="{% url 'datasets:update_protocol' i.id %}">Edit</a></td>    
                </tr>
                {% endfor %}
                {% else %}
                <p>There are no objects saved in the {{ model_name }} list, please create one.</p>
                {% endif %}
            </tbody>
        </table>
        <div class="card-footer d-grid gap-2">
                <a class="btn btn-primary " href="{% url 'datasets:create_protocol' %}">Add {{ model_name }}</a>
        </div>
    </div>

    {% else %}
        <div class="container text-center">
            <p>Please login to view data.</p>
            <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        </div>
{% endif %}   
</div>
{% endblock %}

templates/datasets/task_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <div class="container text-center">
            <h4>Hello {{user.username }}!</h4>
            <p><a href="{% url 'logout' %}">Log Out</a></p>
        </div>
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">{{ model_name }}</h4>
        </div>

        <table class="table card-body">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead >
            <tbody>
                {% if list %}
                {% for i in list %}
                <tr>
                    <td>{{ i.name }}</td>
                    <td><a class="btn btn-primary" href="{% url 'datasets:update_task' i.id %}">Edit</a></td>    
                </tr>
                {% endfor %}
                {% else %}
                <p>There are no objects saved in the {{ model_name }} list, please create one.</p>
                {% endif %}
            </tbody>
        </table>
        <div class="card-footer d-grid gap-2">
                <a class="btn btn-primary " href="{% url 'datasets:create_task' %}">Add {{ model_name }}</a>
        </div>
    </div>

    {% else %}
        <div class="container text-center">
            <p>Please login to view data.</p>
            <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        </div>
{% endif %}   
</div>
{% endblock %}