data/urls.py
# data/urls.py
from django.urls import path
from . import views
# from .views import ActivityListView

app_name = 'data'

urlpatterns = [

    # path('activities/', ActivityListView.as_view(), name='list_activities'),
    path('activity/new/', views.activity_create, name = 'create_activity'),
    path('acitivity/edit/<int:pk>/', views.activity_edit, name='update_activity'),

    # dynamic views
    path('activities/<int:pk>', views.activity_view ,name='view_activities'),
    path('activities/<int:pk>/new/', views.activity_new, name='new_activity'),

]

datasets/urls.py
# datasets.urls

# data/urls.py
from django.urls import path
from . import views

from .views import home, DatasetList, DatasetCreate, DatasetUpdate, delete_model, update_fields, ProtocolList, ProtocolCreate, ProtocolUpdate, TaskList, TaskCreate, TaskUpdate

app_name = 'datasets'

urlpatterns = [
    path('',home,name='home'),
    path('datasets/', DatasetList.as_view(), name='list_datasets'),
    path('datasets/create/', DatasetCreate.as_view(), name='create_dataset'),
    path('datasets/update/<int:pk>/', DatasetUpdate.as_view(), name='update_dataset'),
    path('datasets/delete-model/<int:pk>/', delete_model, name='delete_model'),
    path('datasets/model/<int:pk>/', update_fields, name='update_fields'),

    path('protocols/', ProtocolList.as_view(), name='list_protocols'),
    path('protocols/create/', ProtocolCreate.as_view(), name='create_protocol'),
    path('protocols/update/<int:pk>/', ProtocolUpdate.as_view(), name='update_protocol'),

    path('tasks/', TaskList.as_view(), name='list_tasks'),
    path('tasks/create/', TaskCreate.as_view(), name='create_task'),
    path('tasks/update/<int:pk>/', TaskUpdate.as_view(), name='update_task'),
]

locations/urls.py
# location/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.location, name='location'),
]

npt_data/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('datasets.urls')),
    path('data/', include('data.urls')),
    path('locs/', include('locations.urls')),
]

locations/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    name = models.CharField('Location Name', max_length = 50)

    def __str__(self):
        return self.name

locations/views.py
# locations/views.py
from django.shortcuts import render

# Create your views here.
def location(request):
    return render(request, 'location.html', {})

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

        <title>NPTDS</title>

    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">NPTDS</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page"  href="{% url 'datasets:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'datasets:list_datasets' %}">Datasets</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>


        <div class="container text-center">
            <h1>Nez Perce Tribe Data System</h1>
        </div>

    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    </body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="container text-center">
        {% if user.is_authenticated %}
            <h4>Hello {{user.username }}!</h4>
            <p><a href="{% url 'logout' %}">Log Out</a></p>
            <div class="card">
                <div class="card-header">
                    <h3>Please make a selection</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'datasets:list_tasks' %}">Project/Tasks</a>
                        </div>
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'datasets:list_protocols' %}">Protocols</a>
                        </div>
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'datasets:list_datasets' %}">Datasets</a>
                        </div>
                    </div>
                    {% comment %} <div class="row">
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'datasets:list_locations' %}">Locations</a>
                        </div>
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'datasets:list_tasks' %}">Tasks</a>
                        </div>
                    </div> {% endcomment %}
                </div>
            </div>
        {% else %}
            <p>Please login to view data.</p>
            <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        {% endif %}   
    </div> 
</div>
{% endblock %}

templates/location.html
<h1>This is locations.</h1>